# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_request_number', models.CharField(default='', max_length=10, verbose_name='Part Request Number')),
                ('order', models.PositiveIntegerField(default='', verbose_name='Step Number')),
                ('performed', models.NullBooleanField(verbose_name='Complete')),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StepOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Step Option')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Step', to='autocomplete.Step')),
            ],
        ),
        migrations.AddField(
            model_name='routestep',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Step+', to='autocomplete.Step'),
        ),
        migrations.AddField(
            model_name='routestep',
            name='step_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Option', to='autocomplete.StepOption'),
        ),
    ]
